id = "tmux"
name = "tmux"
version = "0.0.3"
schema_version = 1
authors = ["Dang Huynh <huynhminhdang@gmail.com>"]
description = "Syntax highlighting for tmux configuration files"
repository = "https://github.com/dangh/zed-tmux"

[grammars.tmux]
repository = "https://github.com/Freed-Wu/tree-sitter-tmux"
commit = "26c21424955a719bfdbb3f595265a5322200c261"
